// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo1jyrGO1pAq2EUZJOR7QG2XRMxF9IpdI',
    appId: '1:186424372367:web:ec5a71ce5265b7a91354fa',
    messagingSenderId: '186424372367',
    projectId: 'flutter-project-90c05',
    authDomain: 'flutter-project-90c05.firebaseapp.com',
    storageBucket: 'flutter-project-90c05.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLu24InqniatCqyiXdi-bSln7hViyaxlw',
    appId: '1:186424372367:android:3f8cafbdf8de816d1354fa',
    messagingSenderId: '186424372367',
    projectId: 'flutter-project-90c05',
    storageBucket: 'flutter-project-90c05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZi2BU2ozOu-2UxIDN3zxQVuBSfxG6ieI',
    appId: '1:186424372367:ios:d1f9e5f0f9ec2ce51354fa',
    messagingSenderId: '186424372367',
    projectId: 'flutter-project-90c05',
    storageBucket: 'flutter-project-90c05.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZi2BU2ozOu-2UxIDN3zxQVuBSfxG6ieI',
    appId: '1:186424372367:ios:d1f9e5f0f9ec2ce51354fa',
    messagingSenderId: '186424372367',
    projectId: 'flutter-project-90c05',
    storageBucket: 'flutter-project-90c05.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
